_extends: release-drafter-test:.github/release-drafter-_base.yml # extend元の設定ファイルをリポジトリ名:ファイルパスで指定
name-template: alpha/v$RESOLVED_VERSION # リリースノートのタイトルはタグ名と同じにする
tag-template: alpha/v$RESOLVED_VERSION # タイトルとタグ名を同じにする
tag-prefix: alpha/v
include-paths:
  - "apps/alpha/"
  - "shared/"

categories:
  - title: 'リリース前にbackendのデプロイが必要です'
    labels:
      - 'required: backend'
  - title: リリースOK
    labels:
      - リリースOK
  - title: その他（リリースOKか実装者に要確認）
    labels:
      - '*'
