autolabeler:
  - label: 'alpha'
    files:
      - 'apps/alpha/**/*'
  - label: 'bravo'
    files:
      - 'apps/bravo/**/*'
  - label: 'charlie'
    files:
      - 'apps/charlie/**/*'
  - label: 'shared'
    files:
      - 'shared/**/*'

template: |
  ## Changes

  $CHANGES